---
title: "programacion R"
format: html
editor: visual
toc: true
toc-location: left
number-sections: true
embed-resources: true
output-file: index 
---

# Librerias

```{r}
source('https://inkaverse.com/setup.r')
```

# Modelos lineales mixtos

## Importar datos

```{r}
Datos <- read.csv(file = "LA MOLINA 2014 POTATO WUE (FB) - fb.csv", header = TRUE, sep = ",")
```

## Visualización de data

```{r}
View(Datos)
str(Datos)
```

## Modelos lineal (lfa)

A continuacion se realizara un ANOVA de la variable lfa y su interaccion con el riego y genoma:

```{r}
modelo <- aov(formula = lfa~bloque+riego+geno+riego*geno,data=Datos)
anova(modelo)
plot(modelo)
```

### Boxplot

```{r}
ggplot(Datos, aes(x = geno, y = lfa, colour = riego)) +
  geom_boxplot(outlier.colour = "blue", outlier.shape = 16, outlier.size = 3) +
  labs(title = "Boxplot por Nivel de Riego y Genotipo", x = "Combinación Riego-Genotipo", y = "Area foliar (cm^2)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Modelo lineal (hi)

A continuacion se realizara un ANOVA de la variable hi y su interaccion con el riego y genoma:

```{r}
MODELO<-aov(formula = hi~bloque+riego+geno+riego*geno,data=Datos)
anova(MODELO)
plot(MODELO)
```

### Boxplot

```{r}
ggplot(Datos, aes(x = geno, y = hi, colour = riego)) +
  geom_boxplot(outlier.colour = "yellow", outlier.shape = 16, outlier.size = 3) +
  labs(title = "Boxplot por Nivel de Riego y Genotipo", x = "Combinación Riego-Genotipo", y = "Area foliar (cm^2)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Modelo lineal mixto (lfa)

```{r}
library(lme4)
MODEL3 <- lme4::lmer(lfa~riego+geno+riego*geno+(1|bloque),data = Datos)
anova(MODEL3)
```
